source 'https://ruby.taobao.org/'

gem 'test-kitchen'
gem 'kitchen-docker'

gem 'berkshelf'
gem 'docker'

gem 'busser'
gem 'serverspec', '>= 1.6'

gem 'chefspec', '~> 4.1.0'
gem 'foodcritic', '~> 4.0.0'
gem 'rubocop', '~> 0.28.0'
