---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpuexecutioncap: 90
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[apache_hadoop::install]
      - recipe[hadoop_spark::install]
      - recipe[apache_hadoop::nn]
      - recipe[apache_hadoop::dn]
      - recipe[hadoop_spark::master]
      - recipe[hadoop_spark::worker]
      - recipe[hadoop_spark::yarn]
      #- recipe[hadoop_spark::historyserver]
    attributes:
         java:
           jdk_version: 8
#           install_flavor: oracle
#           oracle:
#             accept_oracle_download_terms: true
         vagrant: true
         apache_hadoop:
#            version: 2.6.0
            nn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
               public_ips: ["10.0.2.15"]
            use_hadoopworks: "false"
         hadoop_spark:
            user: "spark"
            master:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            worker:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            yarn:
               public_ips: ["10.0.2.15"]
               private_ips: ["10.0.2.15"]
            hadoop:
               distribution: "hadoop"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
